### ISSUE TITLE
esx_rp

### ISSUE THREAD

**Issue by krogfelt32** [ESX-Org/esx_rpchat#1]
when used it is deleting the first word when printing out /OOC and /twt

**Comment by ElRocaYT** [comment]
@krogfelt32 all  the commands are working for you? When I type '/me takes a beer' the chat shows up 'STEAM: /me takes a beer' 
Can you send your cfg list to see the order?

**Comment by nearbyplayer** [comment]
Do you both have [esx_identity](https://github.com/esx-org/esx_identity) installed and on the newest version?

**Comment by CombatVG** [comment]
I am having the same issue as @krogfelt32  just the first word doesnt matter how long it is or what its the first word. and i have the latest esx_identity thats on on here. normal local works fine and shows up on console but the other three cut off.

**Comment by JaroSound** [comment]
Same here.
Not workin. When i type /me message i just get my Name

**Comment by nearbyplayer** [comment]
Do you guys get any errors in your console, because to be honest all of these issues you guys are experiencing I have never personally experienced. Also make sure your chat resource is up to date from FiveM.

**Comment by Miniii** [comment]
I have the same problem. The first argument(aka word) of the command is always omitted.

**Comment by nearbyplayer** [comment]
Are you guys doing "/twt Hello!" Because when I've done that the "Hello!" gets printed.

**Comment by Miniii** [comment]
That's strange that it works for you and not us. When we type "/me does this" it prints "[FirstName] this"
same for the other chat commands.

**Comment by nearbyplayer** [comment]
I'll run it again on my local server and see if I can reproduce the issue, if not there isn't anything I can do besides suggest you go through your addons for conflicts, i.e if you have another "commands" plugin that adds /911 etc disable it.

**Comment by JaroSound** [comment]
My plugins:

start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start rconlog
start scoreboard
start loading

start modelblacklist
start ikonynamapie

start mysql-async
start es_extended
start esx_addonaccount
start esx_society
start cron

start esx_menu_default
start esx_menu_list
start esx_menu_dialog

start essentialmode
start es_admin2
start esplugin_mysql
start async
start esx_identity

start esx_billing
start esx_datastore
start esx_phone
start esx_policejob
start esx_addoninventory

start esx_clotheshop
start esx_skin
start skinchanger

start esx_voice
start esx_atm
start esx_shops
start esx_AdvancedFuel

start esx_vehicleshop
start esx_vehiclelock

start esx_eden_garage
# start esx_garage

start baseevents
start esx_ambulancejob
# start esx_holdupbank
start esx_barbershop
start esx_optionalneeds
start esx_status
start esx_basicneeds
start esx_license
start esx_lscustom
start esx_jobs
start esx_joblisting
start esx_weashops
start esx_sit
start esx_rpchat
start esx_boilerplate

start acl
start ArrestAnims
start disabledispatch

# start esx_drugs

start vk_handsup
# start es_carwash
# start coordsaver
start bob74_ipl
start esx_service
start esx_taxijob
start streetLabel
# start esx_carwash
start showcoords
start esx_mecanojob
start neverwantedcmd
start pNotify
start cv_control
start carhud
start PoliceVehiclesWeaponDeleter

**Comment by nearbyplayer** [comment]
Like I said earlier, try using only ESX plugins, and add in your other scripts, because while only using ESX scripts I don't get that same issue.

[Here is a video of it working.](https://rgrab.pw/i/2ZxTm.mp4)

**Comment by JaroSound** [comment]
I just removed all plugins and left rpchat on.
Its stil not workin and it looks like this:  https://i.imgur.com/1uIshh5.jpg

**Comment by nearbyplayer** [comment]
So what you're looking at is intentional. The OOC and Twitter use your actual Steam name, while Local Chat, Me and Do use your first name from your active character.

**Comment by JaroSound** [comment]
Yes but the prblem is there is no text i write /me blablabla and there is just Jaron:. Thats the problem the text is not displayed.

**Comment by nearbyplayer** [comment]
As you can see in the video, I don't have the same problem.

**Comment by JaroSound** [comment]
:( Can u send me the version that u use?

**Comment by nearbyplayer** [comment]
It's the one on GitHub here.

**Comment by JaroSound** [comment]
I instaled another chat addon that added custom commands and it was workin. Any idea? I need this :(

**Comment by nearbyplayer** [comment]
Try to disable that add-on temporarily and see if that addresses your problem.

**Comment by JaroSound** [comment]
the problem is still i disabled all addons and there is the problem :( 
Just left esx_identity and the problem is still.

**Comment by nearbyplayer** [comment]
I'd suggest making a new folder, and just testing with **freshly downloaded** es_extended, the esx_menu's, async, essentialmode, esplugin_mysql, mysql-async, esx_identity, and esx_rpchat.

**Comment by JaroSound** [comment]
I just fixed this.

I removed the oryginal "start chat' and installed a custom chat.
Now it looks like this https://i.imgur.com/tmxV6yC.jpg

**Comment by nearbyplayer** [comment]
Weird, it should work with the original chat, try redownloading the original chat script.

**Comment by ProxyAcid** [comment]
How do i add new commands
