### ISSUE TITLE
RP name, not steam name

### ISSUE THREAD

**Issue by Soldat20** [ESX-Org/esx_rpchat#12]
Characters first name should be the one seen not the steam name as you can have multiple identities with ESX.

**Comment by ElPumpo** [comment]
Related to https://github.com/ESX-Org/esx_identity/issues/12 and https://github.com/ESX-Org/es_extended/issues/20

**Comment by HumanTree92** [comment]
Yeah i agree with this. I ended up reverting back to the old code to be able to use my identity name instead of steam name. As commands like /me shouldn't use players steam name. Doesn't fit to well for RP. I would understand an option like config.enableesxidentity = true and doing it this way instead of using players steam name it would use their identity name.

**Comment by nearbyplayer** [comment]
The characters steam name is ONLY used for OOC & Tweeting as it was designed to. However, this hasn’t been updated in a long time so I’m not sure that it pulls the clients First name from esx_identity.

**Comment by ElPumpo** [comment]
Yep, RP name was removed for a reason. It is not optimal to check against the database for the player name everytime the player sends a (rp) message. The plan is to add RP name from esx_identity to `ESX.PlayerData`

**Comment by HumanTree92** [comment]
I do see how that the updated version could be better. But yes the downfall is you can't set the new one up to use the RP name yet. Also i have a script that uses /trunk /hood and when someone does those commands it prints in chat every time /trunk is an invalid command.

**Comment by HumanTree92** [comment]
Yes @Soldat20 i did that. But that still doesn't solve the RP Name not Steam name issue.

**Comment by Soldat20** [comment]
Yea I tried everything to get the names to be called, I couldn't get it so I reverted back to and older version for now. Also I was just commenting on your /hood and /trunk comment with the invalid command.

**Comment by nearbyplayer** [comment]
@HumanTree92 if you want it to show RP Name you can either revert like @Soldat20 did. Or you can code it in yourself. @ElPumpo removed it in hopes of updating it with a more efficient method than the one originally published.

**Comment by HumanTree92** [comment]
@nearbyplayer if you look at the 3rd comment you can see that i did revert back to the old one. But i was just stating that it would be nice to have it in the new code. As the new code is cleaner & better. Just the downfall of not having the RP Names.

**Comment by nearbyplayer** [comment]
@HumanTree92 ElPumpo did a good job in it. As he said above he is planning to add RP Names back. However it’s not a feature right now, if you wish to utilize it right now feel free to code it and put in a pull request (if you wish it to be public).

**Comment by ElPumpo** [comment]
@HumanTree92 and @Soldat20  you're registering commands the incorrect way. Use must use the [ES event handlers](https://docs.essentialmode.com/#events) to register a command. It's very unoptimized to register an handler for the `chatMessage` event. Example with ES:
```lua
TriggerEvent('es:addAdminCommand', 'command-here-without-slash', permission-level, function(source, args, user) 
     -- Has permission
end, function(source, args, user) 
     -- Doesn't have permission
end, {help here})
```
Now if you guys really want back the old implementation that used the RP name in chat, then sure I understand and I'll add it back and add it to a configuration file, defaulted to be disabled.

**Comment by ElPumpo** [comment]
There we go, implemented. Update ur stuff and enjoy.

**Comment by GusAhr** [comment]
Can we make es_extended auto grab girst/last name instead of steam name? IE for esx_scoreboard

**Comment by HumanTree92** [comment]
The bad part about the scoreboard using first/last name is it won't show new players. You will have to refresh the scoreboard.
