### ISSUE TITLE
global "_U"

### ISSUE THREAD

**Issue by Parme89** [ESX-Org/esx_rpchat#15]
i get an error regarding server.lua Global "_U"

**Comment by ElPumpo** [comment]
you've not installed esx

**Comment by Parme89** [comment]
What ? Ofc ive installed esx , im using the old version now that doesnt use _U in server.lua and thats working fine ? Why are you so quick closing the threads ?

**Comment by ElPumpo** [comment]
Then you have failed to install this script correctly.

**Comment by Parme89** [comment]
Well its drag and drop. What can possibly go wrong :)
