### ISSUE TITLE
How to fix not a valid command

### ISSUE THREAD

**Issue by HumanTree92** [ESX-Org/esx_rpchat#21]
So i have some other scripts like /trunk or /hood but when i do the commands it always says /trunk is not a valid command! 

How would i go about fixing this?

**Comment by Ultrunz** [comment]
TriggerEvent('es:addCommand', 'command-here-without-slash', function(source, args, user) end, {help here})

add this to a server.lua in the addon you're trying to make a command for

**Comment by HumanTree92** [comment]
Didn't work. Here is the default command.

```
AddEventHandler('chatMessage', function(s, n, m)
	local message = string.lower(m)
	if message == "/hood" then
		CancelEvent()
		--------------
		TriggerClientEvent('hood', s)
	end
end)
```

**Comment by ismailmarzuki2097** [comment]
Hey, can u help me? I have a same trouble here
It open the hood or trunk, but it show a message "/trunk is not a valid command"
