### ISSUE TITLE
server/main:23: null index?

### ISSUE THREAD

**Issue by BlueberryDonut** [ESX-Org/esx_rpchat#24]
Getting same error no matter what chat command i use. Tryed to index a null value? I noticed esx_rpchat was patched a few hours ago so i tried the previous version but same issue, any assitance would be great!

**Comment by nearbyplayer** [comment]
What ESX scripts do you have? This requires the base, identity and a few others.

**Comment by BlueberryDonut** [comment]
esx_identity esx_policejob esx_skin skinchanger cron esx_datastore esx_garage esx_vehicleshop esx_addoninventory esx_addonaccount esx_menu_default esx_menu_list esx_menu_dialog esx_license esx_atm async esx_inventory es_extended esx_society. Ive already changed EnableESXIdentity to true in both society & policejob

**Comment by nearbyplayer** [comment]
I'm assuming you have a database correctly set up as well? (MySQL)

**Comment by BlueberryDonut** [comment]
Correct, im using HeidiSQL, had a few bumps in the road setting up garages and vehicle shop and i cant seem to figure this one out with rpchat

**Comment by BlueberryDonut** [comment]
I moved some of the code around to figure out what function was giving the error message.. which would be 'name = GetCharacterName(source)' meaning that GetCharacterName is an unusable value?? if im guessing correctly haha.. I cant see any faults in the code for this function at the bottom of the script and it matches whats on GitHub perfectly.. im stumped
