### ISSUE TITLE
When I tipe in chat /twt, /do or /me it tipe in chat that /twt, /do or /me and under it it tipe my ingame name and that messange that i tiped in /twt, /do or /me how can I fix it?

### ISSUE THREAD

**Issue by DavidTomanica** [ESX-Org/esx_rpchat#26]
When I tipe in chat /twt, /do or /me it tipe in chat that /twt, /do or /me and under it it tipe my ingame name and that messange that i tiped in /twt, /do or /me how can I fix it?

**Comment by metopatel** [comment]
Are you using EssentialMode/ESX?

**Comment by XvenDeR** [comment]
Open config.lua and change from false to true the specific line, it's in english so just read it.
