### ISSUE TITLE
[Request] Add /twta

### ISSUE THREAD

**Issue by SliderKP** [ESX-Org/esx_rpchat#27]
Command for Anom twits?

**Comment by bsdesire** [comment]
This is pretty easy to do, just copy the actual /twt and modify it. You can have my /dw (which is deepweb anon) and change it to /twta.

`RegisterCommand('dw', function(source, args, rawCommand)
    local playerName = GetPlayerName(source)
    local msg = rawCommand:sub(4)
    local name = getIdentity(source)
    fal = name.firstname .. " " .. name.lastname
    TriggerClientEvent('chat:addMessage', -1, {
        template = '<div style="padding: 0.5vw; margin: 0.5vw; background-color: rgba(126, 2, 2, 0.6); border-radius: 3px;"><i class="fas fa-user-ninja"></i> Deep-Web:<br> {1}</div>',
        args = { fal, msg }
    })
end, false)`

Add that to the server.lua and make your changes as you wish.

And then add the suggestion on client.lua

`TriggerEvent('chat:addSuggestion', '/dw',  _U('dw_help'),  { { name = _U('generic_argument_name'), help = _U('generic_argument_help') } } )`

And on resource stop

`TriggerEvent('chat:removeSuggestion', '/dw')`

**Comment by SliderKP** [comment]
I had added it anyway, thank you very much for giving me an answer, I had forgotten to close the request
