### ISSUE TITLE
Doesn't use character name

### ISSUE THREAD

**Issue by HumanTree92** [ESX-Org/esx_rpchat#8]
Don't know why but when i do /twt it shows my steam name not my character name

**Comment by HumanTree92** [comment]
Fixed it. If you would like to use my fix just copy the code below & replace whats needed. Also added a advert command.

`  TriggerEvent('es:addCommand', 'me', function(source, args, user)
      local name = getIdentity(source)
      TriggerClientEvent("sendProximityMessageMe", -1, source, name.firstname .. " " .. name.lastname, table.concat(args, " "))
  end)

  TriggerEvent('es:addCommand', 'do', function(source, args, user)
      local name = getIdentity(source)
      TriggerClientEvent("sendProximityMessageDo", -1, source, name.firstname .. " " .. name.lastname, table.concat(args, " "))
  end)

  TriggerEvent('es:addCommand', 'twt', function(source, args, user)
  	local name = getIdentity(source)
	TriggerClientEvent('chatMessage', -1, "^0[^4Twitter^0] (^5@" .. name.firstname .. " " .. name.lastname .. "^0)", {30, 144, 255}, table.concat(args, " "))
  end, {help = 'Send a tweet. [IC]'})
  
  TriggerEvent('es:addCommand', 'adv', function(source, args, user)
  	local name = getIdentity(source)
	TriggerClientEvent('chatMessage', -1, "^0[^4Advert^0] (^5" .. name.firstname .. " " .. name.lastname .. "^0)", {30, 144, 255}, table.concat(args, " "))
  end, {help = 'Send a advert. [IC]'})

  TriggerEvent('es:addCommand', 'ooc', function(source, args, user)
  	TriggerClientEvent('chatMessage', -1, "OOC | " .. GetPlayerName(source), {128, 128, 128}, table.concat(args, " "))
  end, {help = 'Send an out of character message to the whole server.'})`

**Comment by nearbyplayer** [comment]
When you tweet it's intended to show your Steam name.

**Comment by HumanTree92** [comment]
I understand that its supposed to show your Steam Name but i prefer it to show your Character name as tweeting is a Character function.

**Comment by nearbyplayer** [comment]
Well, as this is a non-issue and merely a preference I'll close this.
